first version
wojciechblim/todo pull request #1
Opened 2018-02-02 20:47 UTC by wojciechblim

2018-02-02 21:33 UTC, wojciechblim commented
Za dużo kodu w jednym obiekcie? Podzielić ToDoElement na mniejsze?

2018-02-03 21:38 UTC, wojciechblim commented
Myślę że utknąłem. Chciałbym zrobić tak by przy zaznaczaniu checkboxa w ToDoElement on się dodawał do arraya w form. zebym pozniej mogl usunac te niechciane

2018-02-06 13:05 UTC, blimusiek commented on lib/game.js
> +  this.checkBox.addEventListener("click", event=>{
Nie potrzebujesz listenera zeby to ostylowac. Mozna to zrobic z css.
[checkbox](https://css-tricks.com/almanac/selectors/c/checked/)

2018-02-06 13:06 UTC, blimusiek commented
Naprawde niezle zaczyna to wygladac :) :+1:

2018-02-06 13:33 UTC, blimusiek commented
`ToDoElement` jest okej.

2018-02-06 14:05 UTC, blimusiek commented
Odnosnie tego:
> Myślę że utknąłem. Chciałbym zrobić tak by przy zaznaczaniu checkboxa w ToDoElement on się dodawał do arraya w form. zebym pozniej mogl usunac te niechciane

Napisze Ci jak to się robi a Ty sprobuj to zaimplementowac.
Te konstruktory ktore napisales nazywa się Widokami albo Rendererami bo mają swoje odzwierciedlenie w drzewie DOM.
Te Widoki powinny rendewrowac jakies dane. Te dane opakowane w obiekty nazywa się Modelem.
czyli potrzebujesz posiadać kolekcje (zapewne array) instancji modelu Todo w widoku aplikacji i dla kazdej z tych instancji zrobic Widok (u Ciebie to jest `ToDoElement` trzeba  zmienic konstruktor zeby przyjal model) i go wyrenderowac. 
Zrobiles Widok `ToDoElement` jako `EventEmitter` a tak na prawde bedzie latwiej jak model bedzie emitterem. Jak nastapi jakas akcja wewnatrz widoku wtedy na jego modelu emituje sie jakas informacje. Kilka przykladow ponizej:

Tak moze wygladac model:
```javascript
function TodoModel(label, finished) {
  this.id = Math.random();
  this.label = label;
  this.finished = finished
}
TodoModel.prototype = {
  emit() {/* ... */},
  on() {/* ... */},
  off() {/* ... */}
}
```
Cos co trzyma modele Todo np `AppView`:

```javascript

function AppView(root) {
  this.el = document.createElement("div");
  this.el.innerHTML = "<div><button id="addTodo">Add Todo</button></div>";
  this.root = root;
  this.todos = [];
  this.el.addEventListener("click", () => {
    this.addTodo()
  })
}

AppView.prototype = {
  render() {
    this.root.innerHTML = "";
    this.todos.forEach(model => this.root.appendChild(new TodoElement(model).render()))
  }
  addTodo() {
    const todoModel = new TodoModel("blabla", false);
   todoModel.on("finish", (id) => {this.finishTodo()})
    this.todos.push(todoModel);
   this.root.appendChild(new TodoElement(todoModel).render())
  }

  finishTodo(id) {
   const todo = this.todos.find(todo => todo.id === id);
   if (todo) {
    todo.finished = true;
  }
}

```

2018-02-09 19:23 UTC, wojciechblim commented
Wydaje mi sie ze musze miec tez dostep z modelu do view, bo to mi ulatwi sprawe

2018-02-15 09:22 UTC, maciekblim requested changes
Wszystko generalnie wyglada w miare spoko ... tylko Modele nie moga byc tez widokami (mowie tutaj o `TodoModel`)

Podsumowujac jak to poprawisz to wyglada to niezle :1st_place_medal:

2018-02-15 09:22 UTC, blimusiek commented on lib/game.js
> +  this.clearBtn = document.createElement("button");
Model nie jest widokiem i nie ma dostepu do HTMLElementow

2018-02-15 09:22 UTC, blimusiek commented on lib/game.js
> +    Array.from(finishedViews).forEach(item => {
czy `clearAllToDoElements` nie powinno usuwac wszystki elementow a nie tylko te zaznaczone

2018-06-14 04:59 UTC, merged